// import { createTheme } from "@mui/material";
// const mode='light'
// export const theme=createTheme({
//     palette:{
//         mode,...(mode==='light')?{
//             primary:{
//                 main:'#1760a5',
//                 light:'#ffffff'
//             },
//             myBlue:{
//                 main:'#cccccc',
//                 light:'#fff'
//             },secondary:{
//                 main:'#ffffff',
//             },myBlack:{
//                 main:'#000000'
//             },gray:{
//                 main:'#E5E5E5',
//                 light:'#dedede',
//                 dark:'#979797'
//             },
//             mustard:{
//                 main:'#FCA311'
//             },
//             red:{
//                 main:'#A22C29'
//             },
//             myWhite:{
//                 main:'#ffffff'
//             }
//         }:{
//             primary:{
//                 main:'#1760a5',
//                 light:'#ffffff'
//             },
//             myBlue:{
//                 main:'#cccccc',
//                 light:'#fff'
//             },secondary:{
//                 main:'#ffffff',
//             },myBlack:{
//                 main:'#000000'
//             },gray:{
//                 main:'#E5E5E5',
//                 light:'#dedede',
//                 dark:'#979797'
//             },
//             mustard:{
//                 main:'#FCA311'
//             },
//             red:{
//                 main:'#A22C29'
//             },
//             myWhite:{
//                 main:'#ffffff'
//             }
//         }
        
//     },
// })